


#db
spring:
  data:
    mongodb:
      uri: ${DB_URL}
      database: algosheets




#oauth
oauth:
  client:
    id: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}
  redirect:
    uri: ${REDIRECT_URI}



#jwt
jwt:
  secret: ${SECRET}